#!/bin/bash
# Like 'go get' but with pinned package versions. https://github.com/joewalnes/go-getter
set -e
: ${GOPATH?"GOPATH not set"}
: ${1?"Usage: $0 [path-to-go-deps]"}
sed -e 's/#.*//' $1 | grep -v -e '^[[:space:]]*$' | while read PKG HASH; do
  echo "$PKG ($HASH)"
  DEST=$GOPATH/src/$PKG
  go get -d -u $PKG || true
  if [ -d $DEST ]; then
    cd $DEST
    if [ -d "$DEST/.git" ]; then
      git checkout -q $HASH
    elif [ -d "$DEST/.hg" ]; then
      hg update -q -c $HASH
    elif [ -d "$DEST/.bzr" ]; then
      bzr update -q -r $HASH
    elif [ -d "$DEST/.svn" ]; then
      svn update -q -r $HASH
    else
      echo "WARNING: Unrecognized VCS system at $DEST"
    fi
  fi
done
